[[Qt6WebChannel]]
arch = "aarch64"
git-tree-sha1 = "3ec3a1b2cccc31ebc0157880d8dfcad0376e2767"
os = "macos"

    [[Qt6WebChannel.download]]
    sha256 = "59b54f8eeb85302071ef01bea3ce91de98bb1277e9e2470a7245d7c1696b4e5b"
    url = "https://github.com/JuliaBinaryWrappers/Qt6WebChannel_jll.jl/releases/download/Qt6WebChannel-v6.8.2+0/Qt6WebChannel.v6.8.2.aarch64-apple-darwin.tar.gz"
[[Qt6WebChannel]]
arch = "x86_64"
git-tree-sha1 = "5bf0a90ed673f50d0962e70d81cab5305bc04130"
os = "macos"

    [[Qt6WebChannel.download]]
    sha256 = "a750185ba023027d2b49d3f641f7f0d6b53c89ae7be29900ff15f15ca1956d0a"
    url = "https://github.com/JuliaBinaryWrappers/Qt6WebChannel_jll.jl/releases/download/Qt6WebChannel-v6.8.2+0/Qt6WebChannel.v6.8.2.x86_64-apple-darwin.tar.gz"
[[Qt6WebChannel]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f5876ad884d452bada84faf48a468dca5ab7b6f"
os = "windows"

    [[Qt6WebChannel.download]]
    sha256 = "8653b05eb92dad18a46604942d4fd35497a86d6ea19c6ac29bcc44a2b94a29d9"
    url = "https://github.com/JuliaBinaryWrappers/Qt6WebChannel_jll.jl/releases/download/Qt6WebChannel-v6.8.2+0/Qt6WebChannel.v6.8.2.i686-w64-mingw32-cxx11.tar.gz"
[[Qt6WebChannel]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6197e9b2ee7e2917482e900aa9d24e800d9433a4"
os = "windows"

    [[Qt6WebChannel.download]]
    sha256 = "4eac68bd96e5fca2db87772489279f38e97dc9af659964816be8bb9191b076bc"
    url = "https://github.com/JuliaBinaryWrappers/Qt6WebChannel_jll.jl/releases/download/Qt6WebChannel-v6.8.2+0/Qt6WebChannel.v6.8.2.x86_64-w64-mingw32-cxx11.tar.gz"
[[Qt6WebChannel]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "00ac9a65a266c7268f432ccf4bf1daffcac8cc18"
libc = "glibc"
os = "linux"

    [[Qt6WebChannel.download]]
    sha256 = "146b2fc61936943aa4baa0da3c5f19f206fb252e470b9d57d731738595595f5c"
    url = "https://github.com/JuliaBinaryWrappers/Qt6WebChannel_jll.jl/releases/download/Qt6WebChannel-v6.8.2+0/Qt6WebChannel.v6.8.2.aarch64-linux-gnu-cxx11.tar.gz"
[[Qt6WebChannel]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "33e7e074cf280dc67b7cbe5a37ae179c3b2474e6"
libc = "musl"
os = "linux"

    [[Qt6WebChannel.download]]
    sha256 = "68d0ae3c29964dfc83a8734f1d3050d6db22dcd58addec0c4f6fce3ebb7d824f"
    url = "https://github.com/JuliaBinaryWrappers/Qt6WebChannel_jll.jl/releases/download/Qt6WebChannel-v6.8.2+0/Qt6WebChannel.v6.8.2.aarch64-linux-musl-cxx11.tar.gz"
[[Qt6WebChannel]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc45a85eaddc66daf31b96a5ede0028574542c56"
libc = "glibc"
os = "linux"

    [[Qt6WebChannel.download]]
    sha256 = "f110ab79721cdbdf2fea48b6dec70e05a12793649b9b0bd3c357dd424f107790"
    url = "https://github.com/JuliaBinaryWrappers/Qt6WebChannel_jll.jl/releases/download/Qt6WebChannel-v6.8.2+0/Qt6WebChannel.v6.8.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Qt6WebChannel]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "49ea3ecd7ed42172ea06676af0f398bdbf09193e"
libc = "musl"
os = "linux"

    [[Qt6WebChannel.download]]
    sha256 = "7f5382c354693502aed8417475b36cb6a7813ced8bf17030f4c4486ece8f29f1"
    url = "https://github.com/JuliaBinaryWrappers/Qt6WebChannel_jll.jl/releases/download/Qt6WebChannel-v6.8.2+0/Qt6WebChannel.v6.8.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Qt6WebChannel]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea44ff87b28495cea5eb1774e9eb134fc2f7e3b5"
libc = "glibc"
os = "linux"

    [[Qt6WebChannel.download]]
    sha256 = "c7680aa5d427a575164a8cdabd08fa4f1c10221d74bd5a6e85d8b3e4d4bc5273"
    url = "https://github.com/JuliaBinaryWrappers/Qt6WebChannel_jll.jl/releases/download/Qt6WebChannel-v6.8.2+0/Qt6WebChannel.v6.8.2.i686-linux-gnu-cxx11.tar.gz"
[[Qt6WebChannel]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "26cadd9271d0cc2792fa669c9ad482f912f042f5"
libc = "musl"
os = "linux"

    [[Qt6WebChannel.download]]
    sha256 = "6efa7ad42c483ff7c617f2debc8585349f20726df54caebb561b442ef5efcb8b"
    url = "https://github.com/JuliaBinaryWrappers/Qt6WebChannel_jll.jl/releases/download/Qt6WebChannel-v6.8.2+0/Qt6WebChannel.v6.8.2.i686-linux-musl-cxx11.tar.gz"
[[Qt6WebChannel]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5cda677ad2e1e3aaf8c1c90b6c3f0d2a87adc0fd"
libc = "glibc"
os = "linux"

    [[Qt6WebChannel.download]]
    sha256 = "882bce70e5dfa19f8b3e8a75b89647a8460824a8dad30c8e7fe3de1175f6713c"
    url = "https://github.com/JuliaBinaryWrappers/Qt6WebChannel_jll.jl/releases/download/Qt6WebChannel-v6.8.2+0/Qt6WebChannel.v6.8.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Qt6WebChannel]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "41b4b15c24115990dbb0d4a60a928ae6d2ec8b34"
libc = "glibc"
os = "linux"

    [[Qt6WebChannel.download]]
    sha256 = "758fd15d20209d8e7f8898141ed9cdd87eeb9e31dcfb4a47044e007e9094e6da"
    url = "https://github.com/JuliaBinaryWrappers/Qt6WebChannel_jll.jl/releases/download/Qt6WebChannel-v6.8.2+0/Qt6WebChannel.v6.8.2.x86_64-linux-gnu-cxx11.tar.gz"
[[Qt6WebChannel]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f5185a6ea53dad8907dbf0cc2d9177a11ff8b986"
libc = "musl"
os = "linux"

    [[Qt6WebChannel.download]]
    sha256 = "d555bc47e9a4a432369354cb33344e4d81af5552190e8c86832b666dfa25d854"
    url = "https://github.com/JuliaBinaryWrappers/Qt6WebChannel_jll.jl/releases/download/Qt6WebChannel-v6.8.2+0/Qt6WebChannel.v6.8.2.x86_64-linux-musl-cxx11.tar.gz"
[[Qt6WebChannel]]
arch = "x86_64"
git-tree-sha1 = "1559ae86e23bd9fa786564e7da475b15f32ab055"
os = "freebsd"

    [[Qt6WebChannel.download]]
    sha256 = "0917444b29d9f95d1dccdd2e0bf3f75df4910223ebff3dbebfa8f326edf1d62c"
    url = "https://github.com/JuliaBinaryWrappers/Qt6WebChannel_jll.jl/releases/download/Qt6WebChannel-v6.8.2+0/Qt6WebChannel.v6.8.2.x86_64-unknown-freebsd.tar.gz"
